name: 'Docker Tag Exists'
description: 'Custom GitHub Action to check if a tag exists on a Docker Repository'
author: 'Hipcamp'
inputs:
  username:
    required: false
    description: 'dockerhub username'
    default: ''
  password:
    required: false
    description: 'dockerhub password'
    default: ''
  image:
    required: true
    description: 'docker image'
  tag:
    required: true
    description: 'tag to check'
outputs:
  tag-exists:
    description: 'tag has exact match'
runs:
  using: 'node12'
  main: 'dist/index.js'
